import React, { useEffect, useState } from 'react';
import { Browser } from '@capacitor/browser';
import type { GithubRelease } from '../utils/updateChecker';

type VisualTheme = 'default' | 'aero';
type SectionId = 'theme' | 'fraction' | 'decimal' | 'layout' | 'about' | 'updates';

interface SettingsModalProps {
    isOpen: boolean; onClose: () => void; darkMode: boolean; toggleTheme: () => void;
    visualTheme: VisualTheme; onVisualThemeChange: (theme: VisualTheme) => void;
    fractionDenominator: number; onFractionDenominatorChange: (denominator: number) => void;
    normalDecimalPlaces: number; onNormalDecimalPlacesChange: (places: number) => void;
    engineeringDecimalPlaces: number; onEngineeringDecimalPlacesChange: (places: number) => void;
    orientation: 'auto' | 'portrait' | 'landscape'; onOrientationChange: (orientation: 'auto' | 'portrait' | 'landscape') => void;
    onCheckForUpdates: () => Promise<GithubRelease | null>; onStartUpdate: (release: GithubRelease) => void; version: string;
}

export const SettingsModal: React.FC<SettingsModalProps> = (props) => {
    const { isOpen, onClose, darkMode, toggleTheme, visualTheme, onVisualThemeChange, fractionDenominator, onFractionDenominatorChange, normalDecimalPlaces, onNormalDecimalPlacesChange, engineeringDecimalPlaces, onEngineeringDecimalPlacesChange, orientation, onOrientationChange, onCheckForUpdates, onStartUpdate, version } = props;
    const [activeSection, setActiveSection] = useState<SectionId | null>(null);
    const [isCheckingUpdates, setIsCheckingUpdates] = useState(false);
    const [updateMessage, setUpdateMessage] = useState('');
    const [availableVersion, setAvailableVersion] = useState('');
    const [availableRelease, setAvailableRelease] = useState<GithubRelease | null>(null);

    useEffect(() => { if (!isOpen) { setActiveSection(null); setUpdateMessage(''); setAvailableVersion(''); setAvailableRelease(null); } }, [isOpen]);
    if (!isOpen) return null;

    const sections: Array<{ id: SectionId; title: string; description: string; icon: string }> = [
        { id: 'theme', title: 'Tema', description: `${visualTheme === 'aero' ? 'Aero Glass' : 'Varsayılan'} · ${darkMode ? 'Karanlık' : 'Aydınlık'} renk`, icon: '◐' },
        { id: 'fraction', title: 'Kesir Hassasiyeti', description: `Yakın kesir: 1/${fractionDenominator}`, icon: '½' },
        { id: 'decimal', title: 'Ondalık Hane', description: `Hesap Makinesi ${normalDecimalPlaces} · Mühendislik ${engineeringDecimalPlaces}`, icon: '0.0' },
        { id: 'layout', title: 'Görünüm', description: orientation === 'auto' ? 'Otomatik yönlendirme' : orientation === 'portrait' ? 'Dikey görünüm' : 'Yatay görünüm', icon: '▣' },
        { id: 'about', title: 'Hakkında', description: `Construction Calc · Sürüm ${version}`, icon: 'i' },
        { id: 'updates', title: 'Güncellemeler', description: 'Yeni sürüm denetimi', icon: '↻' },
    ];
    const choice = (selected: boolean, title: string, detail: string, onClick: () => void) => <button type="button" onClick={onClick} className={`min-h-[72px] rounded-2xl border p-4 text-left transition-all ${selected ? 'border-amber-500 bg-amber-500 text-white shadow-md' : 'border-gray-200 bg-gray-100 text-gray-800 dark:border-gray-700 dark:bg-[#1C2024] dark:text-gray-100'}`}><span className="flex justify-between text-sm font-bold">{title}<span>{selected ? '✓' : ''}</span></span><span className={`mt-1 block text-xs ${selected ? 'text-white/80' : 'text-gray-500 dark:text-gray-400'}`}>{detail}</span></button>;
    const closeSubPanel = () => setActiveSection(null);
    const section = sections.find((item) => item.id === activeSection);

    const subPanel = activeSection && section && <div className="absolute inset-x-0 bottom-0 top-[81px] z-20 flex min-h-0 flex-col bg-white dark:bg-[#2C3035]">
        <div className="flex shrink-0 items-center gap-3 border-b border-gray-200 px-5 py-4 dark:border-gray-700"><button type="button" onClick={closeSubPanel} className="flex h-10 w-10 items-center justify-center rounded-xl bg-gray-100 text-xl text-gray-600 dark:bg-[#1C2024] dark:text-gray-200">‹</button><div><h3 className="text-base font-bold text-gray-900 dark:text-white">{section.title}</h3><p className="text-xs text-gray-500 dark:text-gray-400">Seçiminizi yapın</p></div></div>
        <div className="min-h-0 flex-1 overflow-y-auto p-5">
            {activeSection === 'theme' && <div className="space-y-6"><div><p className="mb-3 text-xs font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400">Tema</p><div className="grid gap-3">{choice(visualTheme === 'default', 'Varsayılan', 'Net yüzeyler ve klasik Construction Calc görünümü.', () => onVisualThemeChange('default'))}{choice(visualTheme === 'aero', 'Aero Glass', 'Renkleri koruyan yarı saydam cam yüzeyler.', () => onVisualThemeChange('aero'))}</div></div><div><p className="mb-3 text-xs font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400">Renkler</p><div className="grid grid-cols-2 gap-3">{choice(darkMode, 'Karanlık Mod', 'Koyu arayüz', () => { if (!darkMode) toggleTheme(); })}{choice(!darkMode, 'Aydınlık Mod', 'Açık arayüz', () => { if (darkMode) toggleTheme(); })}</div></div></div>}
            {activeSection === 'fraction' && <div><p className="mb-4 text-sm text-gray-500 dark:text-gray-400">Ölçü sonuçlarını seçilen en yakın kesre yuvarlar.</p><div className="grid grid-cols-3 gap-3">{[2, 4, 8, 16, 32, 64].map((value) => <button key={value} type="button" onClick={() => onFractionDenominatorChange(value)} className={`min-h-[56px] rounded-2xl border font-mono font-bold ${fractionDenominator === value ? 'border-amber-500 bg-amber-500 text-white' : 'border-gray-200 bg-gray-100 text-gray-700 dark:border-gray-700 dark:bg-[#1C2024] dark:text-gray-200'}`}>1/{value}</button>)}</div></div>}
            {activeSection === 'decimal' && <div className="space-y-4"><p className="text-sm text-gray-500 dark:text-gray-400">Sonuçlarda noktadan sonra gösterilecek hane sayısı.</p>{[['Hesap Makinesi', normalDecimalPlaces, onNormalDecimalPlacesChange], ['Mühendislik', engineeringDecimalPlaces, onEngineeringDecimalPlacesChange]].map(([label, value, onChange]) => <div key={label as string} className="space-y-3 rounded-2xl bg-gray-100 p-4 dark:bg-[#1C2024]"><span className="text-sm font-semibold text-gray-700 dark:text-gray-200">{label as string}</span><div className="grid grid-cols-6 gap-2">{[1, 2, 3, 4, 5, 6].map((places) => <button key={places} type="button" onClick={() => (onChange as (n: number) => void)(places)} className={`h-10 rounded-xl font-bold ${(value as number) === places ? 'bg-amber-500 text-white' : 'bg-white text-gray-700 dark:bg-[#252c34] dark:text-gray-200'}`}>{places}</button>)}</div></div>)}</div>}
            {activeSection === 'layout' && <div><p className="mb-4 text-sm text-gray-500 dark:text-gray-400">Uygulama yönünü seçin.</p><div className="grid gap-3">{([['auto', 'Otomatik', 'Cihaz yönüne uyum sağlar.'], ['portrait', 'Dikey', 'Dikey görünümü sabitler.'], ['landscape', 'Yatay', 'Yatay görünümü sabitler.']] as const).map(([value, label, detail]) => choice(orientation === value, label, detail, () => onOrientationChange(value)))}</div></div>}
            {activeSection === 'about' && <div className="space-y-4"><div className="rounded-3xl bg-[#363636] p-6 text-white shadow-lg"><img src="./construction-calc-logo.png" alt="Construction Calc" className="h-10 w-48 object-contain object-left" /><p className="mt-5 text-lg font-semibold leading-snug">Ölçü ve mühendislik hesapları için güvenilir, hızlı çalışma alanı.</p><p className="mt-2 text-sm leading-relaxed text-white/75">Construction Calc; saha ve ofiste ihtiyaç duyulan ölçü girişlerini, kesirleri, dönüşümleri ve işlem geçmişini tek bir yalın ekranda bir araya getirir.</p></div><div className="grid grid-cols-3 gap-2">{[['Ölçü', 'Feet · Inch · Yard'], ['Hesap', 'Alan · Hacim'], ['Geçmiş', 'Tape kaydı']].map(([title, text]) => <div key={title} className="rounded-2xl bg-gray-100 p-3 text-center dark:bg-[#1C2024]"><div className="text-xs font-bold text-gray-800 dark:text-gray-100">{title}</div><div className="mt-1 text-[10px] text-gray-500 dark:text-gray-400">{text}</div></div>)}</div><div className="rounded-2xl border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-[#1C2024]"><div className="flex justify-between text-sm"><span className="text-gray-500 dark:text-gray-400">Uygulama sürümü</span><span className="font-mono font-bold text-primary">{version}</span></div><button type="button" onClick={() => Browser.open({ url: 'https://github.com/GloriousApps/Construction-Calc' })} className="mt-4 flex w-full justify-between border-t border-gray-200 pt-4 text-sm dark:border-gray-700"><span className="font-medium text-gray-700 dark:text-gray-200">Açık kaynak projesi</span><span className="font-medium text-blue-500">GloriousApps ↗</span></button></div></div>}
            {activeSection === 'updates' && <div className="space-y-4"><p className="text-sm leading-relaxed text-gray-500 dark:text-gray-400">Yeni uygulama sürümü olup olmadığını şimdi kontrol edin.</p><button type="button" disabled={isCheckingUpdates} onClick={async () => { setIsCheckingUpdates(true); setUpdateMessage('Kontrol ediliyor…'); try { const found = await onCheckForUpdates(); setAvailableRelease(found); setAvailableVersion(found?.tag_name || ''); setUpdateMessage(found ? `${found.tag_name} sürümü hazır.` : 'Uygulamanız Güncel ✅'); } catch { setAvailableRelease(null); setAvailableVersion(''); setUpdateMessage('Güncelleme kontrolü başarısız oldu.'); } finally { setIsCheckingUpdates(false); } }} className="min-h-[60px] w-full rounded-2xl bg-[#0b3aa5] font-bold text-white shadow-lg disabled:opacity-70">↻ {isCheckingUpdates ? 'Kontrol ediliyor…' : 'Güncellemeleri denetle'}</button>{updateMessage && <div className={`rounded-2xl border p-4 text-center text-sm font-semibold ${availableVersion ? 'border-blue-300 bg-blue-50 text-blue-800' : 'border-emerald-300 bg-emerald-50 text-emerald-800'}`}>{updateMessage}</div>}{availableRelease && <button type="button" onClick={() => onStartUpdate(availableRelease)} className="min-h-[60px] w-full rounded-2xl bg-emerald-600 font-bold text-white shadow-lg active:translate-y-px">{availableRelease.tag_name} Sürümünü İndir ve Güncelle 🌐</button>}</div>}
        </div>
    </div>;

    return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"><div className="relative flex h-[min(760px,90dvh)] max-h-[90dvh] w-full max-w-sm flex-col overflow-hidden rounded-3xl border border-gray-100 bg-white shadow-2xl dark:border-gray-700 dark:bg-[#2C3035]"><div className="flex shrink-0 items-center justify-between border-b border-gray-100 bg-gray-50 px-6 py-5 dark:border-gray-700 dark:bg-[#25282C]"><h2 className="text-xl font-bold text-gray-900 dark:text-white">⚙️ Ayarlar</h2><button type="button" onClick={onClose} className="rounded-full bg-gray-200 px-3 py-1 text-xl text-gray-600 dark:bg-gray-700 dark:text-gray-300">×</button></div><div className="min-h-0 flex-1 overflow-y-auto p-5"><p className="mb-4 px-1 text-xs text-gray-500 dark:text-gray-400">Bir ayar kartı seçerek seçenekleri ayrı pencerede açın.</p><div className="space-y-3">{sections.map((item) => <button key={item.id} type="button" onClick={() => setActiveSection(item.id)} className="group flex min-h-[80px] w-full items-center gap-4 rounded-2xl border border-gray-200 bg-gray-100 px-4 py-4 text-left shadow-sm dark:border-gray-700 dark:bg-[#1C2024]"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#252d36] text-lg font-bold text-amber-400">{item.icon}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold uppercase tracking-wider text-gray-700 dark:text-gray-200">{item.title}</span><span className="mt-1 block truncate text-xs text-gray-500 dark:text-gray-400">{item.description}</span></span><span className="text-gray-400">›</span></button>)}</div></div>{subPanel}</div></div>;
};
